"""initial migration

Revision ID: 0162407dd237
Revises: 
Create Date: 2017-12-18 11:33:18.342347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0162407dd237'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.add_column('user_collection', sa.Column('users_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_collection_user_id_fkey', 'user_collection', type_='foreignkey')
    op.create_foreign_key(None, 'user_collection', 'dogs', ['users_id'], ['id'])
    op.drop_column('user_collection', 'user_id')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.add_column('user_collection', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_collection', type_='foreignkey')
    op.create_foreign_key('user_collection_user_id_fkey', 'user_collection', 'dogs', ['user_id'], ['id'])
    op.drop_column('user_collection', 'users_id')
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dod_username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email_address', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('dod_username', name='user_dod_username_key'),
    sa.UniqueConstraint('email_address', name='user_email_address_key')
    )
    # ### end Alembic commands ###
