"""username column change

Revision ID: ba116ce846cc
Revises: 
Create Date: 2017-12-13 15:20:21.378847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba116ce846cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('username', sa.String(), nullable=True))
    op.drop_constraint('tweet_user_id_fkey', 'tweet', type_='foreignkey')
    op.create_foreign_key(None, 'tweet', 'user', ['username'], ['id'])
    op.drop_column('tweet', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tweet', type_='foreignkey')
    op.create_foreign_key('tweet_user_id_fkey', 'tweet', 'user', ['user_id'], ['id'])
    op.drop_column('tweet', 'username')
    # ### end Alembic commands ###
