"""initial-migration

Revision ID: cafb8f6d86d3
Revises: 
Create Date: 2017-12-14 20:58:19.340202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cafb8f6d86d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('twitter_username', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'tweet', ['twitter_username'])
    op.add_column('user', sa.Column('in_tweets', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'in_tweets')
    op.drop_constraint(None, 'tweet', type_='unique')
    op.drop_column('tweet', 'twitter_username')
    # ### end Alembic commands ###
